FROM docker.io/nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --break-system-packages pyzmq ipykernel
